### PR TITLE
Fix CI

### PR DESCRIPTION
**Pull request by mnlevy1981**
The driver runs from day 0 through day 364 rather than 1 through 365; I
didn't update the driver test when I made that change

### CODE REVIEW

**Comment by mnlevy1981** [comment]
`build-docs` is still failing for me, but the `pytest` tests are passing now. I don't understand what is different between [my test](https://github.com/marbl-ecosys/feisty/runs/4821375464?check_suite_focus=true) and [the test that ran when merging](https://github.com/marbl-ecosys/feisty/runs/4821300451?check_suite_focus=true)... the former is a link to the failure from this PR and the latter is a link to the same test passing from when @matt-long merged #6 just a few minutes ago.

**Comment by mnlevy1981** [comment]
ac92e91 is a little esoteric, but I think it's what we want: the `build-docs` workflow is used to test that the jupyter book can be created, but doesn't push it to the `gh-pages` branch -- that only happens with the new `build-docs-push-ghpages` workflow, which runs when something is pushed to `main` but does not run on PRs. So the gh-pages webpage is only updated when `main` is updated, rather than when someone opens up a PR with a new branch (which I think we want, because if someone opens a PR that completely borks the docs we can just reject the PR and the main ghpages branch won't be affected)

**Comment by mnlevy1981** [comment]
@matt-long if all tests pass, I think this is ready to be merged (and hopefully the merge will include the `build-docs-push-ghpages` action)

**Comment by matt-long** [comment]
Thanks @mnlevy1981!

**Pull request merged**
